### ISSUE TITLE
Auditwolf - Missing calculation of mintamounts when totalsupply == 0 prevents liquidity providers from adding liquidity to the vaults.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#106]
Auditwolf

high

# Missing calculation of mintamounts when totalsupply == 0 prevents liquidity providers from adding liquidity to the vaults.

## Summary

To determine mint amount, function getmintamounts first checks if total supply > 0 or not. It then calls function computemintamounts with the required data based on the the condition in place. function computemintamount however does not have a way to calculate mint amount on the condition that total supply == 0.
 
## Vulnerability Detail

         if (totalSupply > 0) {
            (uint256 current0, uint256 current1) = UnderlyingHelper
                .totalUnderlyingForMint(
                    underlyingPayload,
                    totalSupply,
                    totalSupply
                );

            mintAmount = UnderlyingHelper.computeMintAmounts(
                current0,
                current1,
                totalSupply,
                amount0Max_,
                amount1Max_
            );
            (amount0, amount1) = UnderlyingHelper.totalUnderlyingForMint(
                underlyingPayload,
                mintAmount,
                totalSupply
            );
        } else {
            mintAmount = UnderlyingHelper.computeMintAmounts(
                vaultV2_.init0(),
                vaultV2_.init1(),
                1 ether,
                amount0Max_,
                amount1Max_
            );
    
Here we can see a call to function computeMintamounts with the required data  if total supply > 0 or not.
Now lets look at function computemintamounts.

        if (current0_ == 0 && current1_ > 0) {
            mintAmount = FullMath.mulDiv(amount1Max_, totalSupply_, current1_);
        } else if (current1_ == 0 && current0_ > 0) {
            mintAmount = FullMath.mulDiv(amount0Max_, totalSupply_, current0_);
        } else if (current0_ > 0 && current1_ > 0) {
            uint256 amount0Mint = FullMath.mulDiv(
                amount0Max_,
                totalSupply_,
                current0_
            );
            uint256 amount1Mint = FullMath.mulDiv(
                amount1Max_,
                totalSupply_,
                current1_
            );
            require(
                amount0Mint > 0 && amount1Mint > 0,
                "ArrakisVaultV2: mint 0"
            );

            mintAmount = amount0Mint < amount1Mint ? amount0Mint : amount1Mint;
        } else {
            revert("ArrakisVaultV2: panic");
        }
    }
Here we see the conditions being checked are only when total supply > 0. Therefore, if total supply ==0 these conditions will not be met hence the function reverts meaning mint amount will not be calculated when total supply == 0.

## Impact
Liquidity providers will not be able to add liquidity if total supply == 0.

## Code Snippet

https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/libraries/Underlying.sol#L355C1-L388C1
https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/ArrakisV2Resolver.sol#L166C1-L194C1

## Tool used

Manual Review

## Recommendation
Add a a way to calculate mint amount in function computemintamounts if totalsupply == 0.

**Comment by htstarz** [comment]
Escalate for 10 usdc
I think this issue was mistakenly judged as a duplicate of #154 which  describes a first minter problem while this issue is about the computation of mint amount with the initial ratios ( init0(), init1() ) which occurs in the else statement of the first  highlighted code .

**Comment by sherlock-admin** [comment]
> Escalate for 10 usdc
> I think this issue was mistakenly judged as a duplicate of #154 which  describes a first minter problem while this issue is about the computation of mint amount with the initial ratios ( init0(), init1() ) which occurs in the else statement of the first  highlighted code .

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
@ctf-sec

**Comment by kassandraoftroy** [comment]
This issue is invalid. If you look at the code we pass totalSupply_ as parameter to the computeMintAmounts function and in teh case when vault.totalSupply() == 0 we use a value of `1 ether` there, so this function runs correctly. Thats why "first mint" does not revert (which you can also see by inspection by deploying a vault and adding the first liquidity into it).

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on Sponsor's comment

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [htstarz](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/106/#issuecomment-1636693219): accepted
