### ISSUE TITLE
alexzoid - Indeterminacy in Vault address generation could lead to unexpected addresses

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#114]
alexzoid

medium

# Indeterminacy in Vault address generation could lead to unexpected addresses

## Summary
Vault contracts are deployed in a similar fashion to Uniswap, utilizing the `create2` opcode. This is designed to ensure that the Vault contract address is predictable and consistent, as certain scenarios necessitate knowing the pool address in advance for operations. However, the existing implementation may not provide a completely deterministic Vault contract address.

## Vulnerability Detail
The vulnerability arises from the usage of `block.number` and `numVaults() + 1` in the `_preDeploy()` function. This function is responsible for computing the address of the pre-deployed contract and deploying it using `create2`. It's impractical to predict the block number where the transaction will be confirmed. Similarly, using `numVaults()`, which retrieves `_vaults.length()` from contract storage, introduces unpredictability. The `_vaults` variable could be altered by preceding transactions that modify it, causing the final vault address to deviate from the calculated one.

## Impact
This indeterminacy could cause users and contracts to use incorrect Vault addresses, which can potentially result in errors or loss of tokens.

## Code Snippet
https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/ArrakisV2Factory.sol#L94-L130

## Tool used
VSCodium

## Recommendation
Instead of using `block.number` and `numVaults() + 1` to calculate the `create2` salt, consider alternative methods that can provide deterministic results, ensuring the consistency of the Vault address generation.

**Comment by alexzoid-eth** [comment]
Escalate

This is a valid medium issue. The purpose of using `create2` with salt here is to predict the `Vault` contract address. However, the mechanism is broken and not deterministic, which may result in operational errors and possibly token loss. 

It's worth noting that a similar issue has been previously reported and acknowledged as valid in another project https://code4rena.com/reports/2022-12-stealth-project#m-02-pool-address-is-not-deterministic-the-actual-pool-address-deployed-may-be-different-from-the-address-computed-in-advance

**Comment by sherlock-admin** [comment]
> Escalate
> 
> This is a valid medium issue. The purpose of using `create2` with salt here is to predict the `Vault` contract address. However, the mechanism is broken and not deterministic, which may result in operational errors and possibly token loss. 
> 
> It's worth noting that a similar issue has been previously reported and acknowledged as valid in another project https://code4rena.com/reports/2022-12-stealth-project#m-02-pool-address-is-not-deterministic-the-actual-pool-address-deployed-may-be-different-from-the-address-computed-in-advance

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
> This is a valid medium issue. The purpose of using create2 with salt here is to predict the Vault contract address. However, the mechanism is broken and not deterministic, which may result in operational errors and possibly token loss.

**Comment by ctf-sec** [comment]
the impact is not high enough to make it as a medium and would difficult to measure the impact of "indeterministic" address.

but I get the report that using block.number to derive the pool address may not be the most ideal way. will bring it for sponsor review

**Comment by hrishibhat** [comment]
Agree with @ctf-sec on the impact of this issue not being significant enough for a medium
cc- @Gevarist

**Comment by Gevarist** [comment]
It's not a valid issue, create force us to follow a certain order of vault creation to match different chains addresses. That's something we cannot do, because some vaults are specific to some chains. That can also introduce confusion to user, the impact can also be loss of fund. Using create2 give us indeterminacy, so users is warned that he should not rely on address to guess the token pair used on that vault.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this a non issue based on the Sponsor comment

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [z0ld](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/114/#issuecomment-1637025048): rejected
