### ISSUE TITLE
0x007 - amount1 would be zero when sqrtRatioX96 == sqrtRatioAX96

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#142]
0x007

medium

# amount1 would be zero when sqrtRatioX96 == sqrtRatioAX96

## Summary
There would be a difference in `amount1` required by Uniswap and `amount1` required by Arrakis when `sqrtRatioX96 == sqrtRatioAX96`.

## Vulnerability Detail
[Uniswap](https://github.com/Uniswap/v3-core/blob/d8b1c635c275d2a9450bd6a78f3fa2484fef73eb/contracts/UniswapV3Pool.sol#L328) checks if `tick < tickLower`. Therefore, if `tick == tickLower`, then the `else if` block would be executed in which amount1 would not be zero. In [Arrakis](https://github.com/sherlock-audit/2023-06-arrakis/blob/4e44c8c63cb4662cd1b082fcea6df82c63438331/v2-core/contracts/libraries/Underlying.sol#L311), amount1 would be zero cause it executes the `if` statement.

## Impact
Uniswap would require 1 unit of token1 but Arrakis vault would take 0 from the user. Arrakis vault would take the amount from the fee available to the vault or revert when its balance is 0.

## Code Snippet
https://github.com/sherlock-audit/2023-06-arrakis/blob/4e44c8c63cb4662cd1b082fcea6df82c63438331/v2-core/contracts/libraries/Underlying.sol#L311
https://github.com/Uniswap/v3-core/blob/d8b1c635c275d2a9450bd6a78f3fa2484fef73eb/contracts/UniswapV3Pool.sol#L328

## Tool used

Manual Review

## Recommendation
change `if (sqrtRatioX96 <= sqrtRatioAX96)` to `if (sqrtRatioX96 < sqrtRatioAX96)`

Duplicate of #8

**Comment by ctf-sec** [comment]
Escalate

duplicate of #8
