### ISSUE TITLE
tsvetanovv - Not check for the valid round in Sequencer

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#161]
tsvetanovv

medium

# Not check for the valid round in Sequencer

## Summary

When checking sequencer uptime, it is mandatory to also check for a valid round.

## Vulnerability Detail

In `ChainLinkOracle.sol` we have `_checkSequencer()`:
```solidity
function _checkSequencer() internal view {
        (, int256 answer, uint256 startedAt, , ) = sequencerUptimeFeed
            .latestRoundData();

        require(answer == 0, "ChainLinkOracle: sequencer down");

        // Make sure the grace period has passed after the
        // sequencer is back up.
        require(
            block.timestamp - startedAt > GRACE_PERIOD_TIME, // solhint-disable-line not-rely-on-time, max-line-length
            "ChainLinkOracle: grace period not over"
        );
    }
```

This function checks the status of the sequencer and ensures that a grace period has passed since the sequencer status changed.
But this function is missing one very important check. According to the Chainlink documentation:

>`startedAt`: This timestamp indicates when the sequencer changed status. This timestamp returns `0` if a round is invalid.

https://docs.chain.link/data-feeds/l2-sequencer-feeds#example-code

## Impact

Failure to check for a valid round will result in an incorrect status of Sequencer. 

## Code Snippet

https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-manager-templates/contracts/oracles/ChainLinkOracle.sol#L148-L161
https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-manager-templates/contracts/oracles/ChainLinkOraclePivot.sol#L277-L290

## Tool used

Manual Review

## Recommendation

Check round validity:

```solidity
require(startedAt != 0, "_checkSequencer(): invalid round")
```

**Comment by cvetanovv** [comment]
Escalate 

This is valid issue. 

From the Sherlock docs we see: `Chainlink round completeness check is invalid. The new OCR does not rely on rounds for reporting.` But this only applies to `latestRoundData`. -> [Reference](https://github.com/sherlock-audit/2022-11-float-capital-judging/issues/4) 
I myself made the suggestion that this be added to the Sherlock documentation as invalid -> [link](https://discord.com/channels/812037309376495636/881726370370158592/1117485716499337256)

But here the case is different. Here we are talking about a completely different function and verification. Until now I have seen absolutely no one reporting this exact problem.

According to the Chainlink documentation for Sequencer:
>`startedAt`: This timestamp indicates when the sequencer changed status. This timestamp returns `0` if a round is invalid.

Open this link from the official documentation and look at the bottom of the page -> [link](https://docs.chain.link/data-feeds/l2-sequencer-feeds#example-code)

**Comment by sherlock-admin** [comment]
> Escalate 
> 
> This is valid issue. 
> 
> From the Sherlock docs we see: `Chainlink round completeness check is invalid. The new OCR does not rely on rounds for reporting.` But this only applies to `latestRoundData`. -> [Reference](https://github.com/sherlock-audit/2022-11-float-capital-judging/issues/4) 
> I myself made the suggestion that this be added to the Sherlock documentation as invalid -> [link](https://discord.com/channels/812037309376495636/881726370370158592/1117485716499337256)
> 
> But here the case is different. Here we are talking about a completely different function and verification. Until now I have seen absolutely no one reporting this exact problem.
> 
> According to the Chainlink documentation for Sequencer:
> >`startedAt`: This timestamp indicates when the sequencer changed status. This timestamp returns `0` if a round is invalid.
> 
> Open this link from the official documentation and look at the bottom of the page -> [link](https://docs.chain.link/data-feeds/l2-sequencer-feeds#example-code)
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Don't think this is a issue because of this validation

```solidity
require(
    block.timestamp - startedAt > GRACE_PERIOD_TIME, // solhint-disable-line not-rely-on-time, max-line-length
    "ChainLinkOracle: grace period not over"
);
```

**Comment by cvetanovv** [comment]
> Don't think this is a issue because of this validation
> 
> ```solidity
> require(
>     block.timestamp - startedAt > GRACE_PERIOD_TIME, // solhint-disable-line not-rely-on-time, max-line-length
>     "ChainLinkOracle: grace period not over"
> );
> ```

That's what makes it vulnerable.  `startedAt` will be 0 and will not do an adequate check of `block.timestamp - startedAt`
If `startedAt` is zero the function need to revert. 

This is from official documentation:
`startedAt:` This timestamp indicates when the sequencer changed status. 
1. **This timestamp returns 0 if a round is invalid.** 
2. When the sequencer comes back up after an outage, wait for the GRACE_PERIOD_TIME to pass before accepting answers from the data feed. 
3. Subtract startedAt from block.timestamp and revert the request if the result is less than the GRACE_PERIOD_TIME.

If step 1 is not validated, then step 3 will return an incorrect result. When it's time to validate step 3. The function will think the round is valid, but it's really not because it doesn't have the validation of step 1. And from there, the function will return the wrong result.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
The code follows chainlink recommendations. Don't see a valid issue with a clear impact here.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [cvetanovv](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/161/#issuecomment-1635994217): rejected
