### ISSUE TITLE
n33k - Missing deviation check on `rebalanceParams_.burns` enables sandwich attack on liquidity burning

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#165]
n33k

medium

# Missing deviation check on `rebalanceParams_.burns` enables sandwich attack on liquidity burning

## Summary

Inside `SimpleManager::rebalance`, deviation check only applied to `rebalanceParams_.mints`. `rebalanceParams_.burns` is missed from this check which makes sandwich attack on liquidity buring possible under certain conditions.

## Vulnerability Detail

Inside `SimpleManager::rebalance`, the `_checkDeviation` function checks within a for loop to ensure that every `rebalanceParams_.mints` pool is not price-manipulated. However, the check does not include the `rebalanceParams_.burns` pools. If `rebalanceParams_.burns` and `rebalanceParams_.mints` are not equal, some of the `rebalanceParams_.burns` pools could be missed by the check.

Inside `ArrakisV2::rebalance`, the liquidities in `rebalanceParams_.burns` pools are burned. The slippage checks are applied to the aggregated results. A sandwich attacker can bypass these checks by pushing up the price of one pool and reducing the price of another. This will counteract the two slippage effects and correct the final aggregated results.

```solidity
    aggregator.burn0 += withdraw.burn0;
    aggregator.burn1 += withdraw.burn1;

    aggregator.fee0 += withdraw.fee0;
    aggregator.fee1 += withdraw.fee1;
}

require(aggregator.burn0 >= rebalanceParams_.minBurn0, "B0");
require(aggregator.burn1 >= rebalanceParams_.minBurn1, "B1");
```

These are all the slippage checkes involved in the liquidity burning process. For a successful sandwich attack on the liquidity burning in the rebalance process, `rebalanceParams_.burns` needs to have at least two pools that do not exist in `rebalanceParams_.mints`. Some legitimate strategies may satisfy this or a malicious operator/keeper bot could post such rebalance payload in order to launch sandwich attack.

## Impact

Protocol lose funds because of sandwich attack on the liquidity burning in the rebalance process.

## Code Snippet

https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-manager-templates/contracts/SimpleManager.sol#L162-L198

https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/ArrakisV2.sol#L298-L306

## Tool used

Manual Review

## Recommendation

Apply `_checkDeviation` check not only to mint pools but also to burn pools.

Duplicate of #84

**Comment by syjcnss** [comment]
Escalate

This is not a dup of #84 but is a dup of #181。

**Comment by sherlock-admin** [comment]
> Escalate
> 
> This is not a dup of #84 and is a combination of #181 and #28 to make a high servity attack.
> 
> > Inside SimpleManager::rebalance, the _checkDeviation function checks within a for loop to ensure that every rebalanceParams_.mints pool is not price-manipulated. However, the check does not include the rebalanceParams_.burns pools. If rebalanceParams_.burns and rebalanceParams_.mints are not equal, some of the rebalanceParams_.burns pools could be missed by the check.
> 
> This is the first one and is the same as #181. Burn pools(rebalanceParams_.burns) are not checked unbalanced(_checkDeviation ) inside router.
> 
> In #181 the watson only bypasses the slippage protection inside SimpleManager. There will be [another slippage check on burn pools](https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/ArrakisV2.sol#L305-L306) in ArrakisV2 during the rebalance to prevent price manipulations on burn pools.
> 
> So I leveraged a second bug to bypass this check to make this attack complete.
> 
> > Inside ArrakisV2::rebalance, the liquidities in rebalanceParams_.burns pools are burned. The slippage checks are applied to the aggregated results. A sandwich attacker can bypass these checks by pushing up the price of one pool and reducing the price of another. This will counteract the two slippage effects and correct the final aggregated results.
> 
> This is the second one and is the same as described in #28.
> 
> The seperated effects of these two bugs are small. The combination of them formed a completed and more profitable attack chian so I made them in one report.

    You've deleted an escalation for this issue.

**Comment by syjcnss** [comment]
I agreed on this comment that sandwich attack liqudity buring will not profit the attacker.

* https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/181#issuecomment-1636305780

This one should at least be a dup of #28.
