### ISSUE TITLE
immeas - any tokens in `ArrakisV2Router` can be claimed using false permit

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#167]
immeas

medium

# any tokens in `ArrakisV2Router` can be claimed using false permit

## Summary
Arrakis V2 uses `Permit2` by uniswap to transfer tokens. However the tokens transferred by `Permit2` are never checked to be the same as `token0`/`1`.

## Vulnerability Detail
When using `Permit2` to transfer tokens via the Router, this call is made:

https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-periphery/contracts/ArrakisV2Router.sol#L605-L621
```solidity
File: v2-periphery/contracts/ArrakisV2Router.sol

605:            require(params_.permit.permitted.length == 2, "length mismatch");
606:            SignatureTransferDetails[]
607:                memory transfers = new SignatureTransferDetails[](2);
608:            transfers[0] = SignatureTransferDetails({
609:                to: address(this),
610:                requestedAmount: amount0_
611:            });
612:            transfers[1] = SignatureTransferDetails({
613:                to: address(this),
614:                requestedAmount: amount1_
615:            });
616:            permit2.permitTransferFrom(
617:                params_.permit,
618:                transfers,
619:                msg.sender,
620:                params_.signature
621:            );
```

The issue here is that which token is used is passed in `params_.permit` hence a user could send whatever ERC20 compliant token there that will be transferred to the router.

Then when adding liquidity the router assumes that `token0`/`1` has been transferred:

https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-periphery/contracts/ArrakisV2Router.sol#L399-L448
```solidity

399:    function _addLiquidity(
            ...
409:    ) internal {
410:        token0_.safeIncreaseAllowance(vault_, amount0In_);
411:        token1_.safeIncreaseAllowance(vault_, amount1In_);
412:
			...
431:
432:        uint256 balance0 = token0_.balanceOf(address(this));
433:        uint256 balance1 = token1_.balanceOf(address(this));
434:        if (gauge_ == address(0)) {
435:            IArrakisV2(vault_).mint(mintAmount_, receiver_);
436:        } else {
                ...
442:        }
443:
444:
445:        require(
446:            balance0 - amount0In_ == token0_.balanceOf(address(this)),
447:            "deposit0"
448:        );
449:        require(
450:            balance1 - amount1In_ == token1_.balanceOf(address(this)),
451:            "deposit1"
452:        );
453:    }
```

If there are `token0`/`1` in the router contract, these can be minted on the callers behalf in the Arrakis vault.

## Impact
An attacker can claim any `token0`/`1` in `ArrakisV2Router`. Since there is no fair way for tokens to end up in Router (only possible by mistake or badly configured vault) hence just medium. Mainly because it is easy to verify that the tokens in the `permit` are the same as in the vault.

See [any tokens in `ArrakisV2Router` can be claimed using `removeLiquidity`](https://github.com/sherlock-audit/2023-06-arrakis-0ximmeas/issues/3) for more discussion about how to deal with tokens accidentally ending up in the router.

## Code Snippet
See above.

## Tool used
Manual Review

## Recommendation
Verify that tokens used in the permit are the same as `token0`/`1`

Duplicate of #194

**Comment by IAm0x52** [comment]
Escalate

This is not a dupe of #183. This discusses stealing funds in the router. Since the router is not intended to hold any funds between trades this should be low

**Comment by sherlock-admin** [comment]
> Escalate
> 
> This is not a dupe of #183. This discusses stealing funds in the router. Since the router is not intended to hold any funds between trades this should be low

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JeffCX** [comment]
Agree with the senior's watson's escalation

**Comment by 0ximmeas** [comment]
Also agree that this isn't a duplicate of https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/183 but rather https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/194 which is consider low

**Comment by hrishibhat** [comment]
Result:
Low
Duplicate of #194 
Considering this issue a low

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [IAm0x52](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/167/#issuecomment-1636899317): accepted
