### ISSUE TITLE
immeas - `DoS` of `RouterSwapExecutor` with large approvals

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#168]
immeas

medium

# `DoS` of `RouterSwapExecutor` with large approvals

## Summary
Similar to https://gist.github.com/kassandraoftroy/6ab217b265b29ce7c33106e5d57bbe4b#1-dos-of-routerswapexecutor-with-non-zero-approvals

## Vulnerability Detail
Similar to the vulnerability https://gist.github.com/kassandraoftroy/6ab217b265b29ce7c33106e5d57bbe4b#1-dos-of-routerswapexecutor-with-non-zero-approvals

When swapping with `RouterSwapExecutor.swap()` a user picks `swapRouter` and `swapPayload`.

https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-periphery/contracts/RouterSwapExecutor.sol#L44-L59
```solidity
File: v2-periphery/contracts/RouterSwapExecutor.sol

44:        if (swapAndAddData_.swapData.zeroForOne) {
45:            balanceBefore = token0.balanceOf(address(this));
46:            token0.safeIncreaseAllowance(
47:                swapAndAddData_.swapData.swapRouter,
48:                swapAndAddData_.swapData.amountInSwap
49:            );
50:        } else {
51:            balanceBefore = token1.balanceOf(address(this));
52:            token1.safeIncreaseAllowance(
53:                swapAndAddData_.swapData.swapRouter,
54:                swapAndAddData_.swapData.amountInSwap
55:            );
56:        }
57:        (bool success, ) = swapAndAddData_.swapData.swapRouter.call(
58:            swapAndAddData_.swapData.swapPayload
59:        );
```

If `swapAndAddData_.swapData.swapRouter` is another token than `token0`/`1`, an attacker can increase the allowance to `type(uint256).max - 1`. That way, when this token is traded. The increase allowance in OZ lib will overflow:

```solidity
File: SafeERC20.sol

60:    function safeIncreaseAllowance(
61:        IERC20 token,
62:        address spender,
63:        uint256 value
64:    ) internal {
65:        uint256 newAllowance = token.allowance(address(this), spender) + value; // if allowance is max - 1 this will overflow
66:        _callOptionalReturn(token, abi.encodeWithSelector(token.approve.selector, spender, newAllowance));
67:    }
```

## Impact
Same as in https://gist.github.com/kassandraoftroy/6ab217b265b29ce7c33106e5d57bbe4b#1-dos-of-routerswapexecutor-with-non-zero-approvals

An attacker can DoS every call to `swapAndAddLiquidity()` by frontrunning.

## Code Snippet
https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-periphery/contracts/RouterSwapExecutor.sol#L44-L59

## Tool used
https://gist.github.com/kassandraoftroy/6ab217b265b29ce7c33106e5d57bbe4b#1-dos-of-routerswapexecutor-with-non-zero-approvals

Manual Review

## Recommendation
Either follow the recommendation in https://gist.github.com/kassandraoftroy/6ab217b265b29ce7c33106e5d57bbe4b#1-dos-of-routerswapexecutor-with-non-zero-approvals and do whitelisting.

Or begin with setting the allowance to `0` before increasing the allowance.

**Comment by 0ximmeas** [comment]
Escalate

I believe my submission to be a valid issue.

The fix done for https://gist.github.com/kassandraoftroy/6ab217b265b29ce7c33106e5d57bbe4b#1-dos-of-routerswapexecutor-with-non-zero-approvals introduced a similar issue with the increased approval reverting on overflow.

The issue https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/202 which this is a duplicate of does bring up the fault but this submission correctly shows how to "twist the knife" and take advantage of it in a way that negatively affects users. In the same way as described in the report linked above. Hence I believe this issue to be valid while the others are not since they don't describe a way of abusing the left over allowances.

**Comment by sherlock-admin** [comment]
> Escalate
> 
> I believe my submission to be a valid issue.
> 
> The fix done for https://gist.github.com/kassandraoftroy/6ab217b265b29ce7c33106e5d57bbe4b#1-dos-of-routerswapexecutor-with-non-zero-approvals introduced a similar issue with the increased approval reverting on overflow.
> 
> The issue https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/202 which this is a duplicate of does bring up the fault but this submission correctly shows how to "twist the knife" and take advantage of it in a way that negatively affects users. In the same way as described in the report linked above. Hence I believe this issue to be valid while the others are not since they don't describe a way of abusing the left over allowances.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
I agree with escalation, issue #202 and all its duplicate can be a valid medium because the operator is considered semi-trusted

**Comment by 0ximmeas** [comment]
Just to be clear, I do agree that https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/202 is not a medium issue since it does not show how to abuse the left over allowance. While here I highlight that leaving a very large allowance can DoS for the "next" user which is a medium issue.

**Comment by ctf-sec** [comment]
Emm, I think swapAndAddData_.swapData.amountInSwap is in the control of the rebalancer, he can set it to 0 if he detect the increaseAllowance is about to overflow, so don't think this is a issue.

**Comment by 0ximmeas** [comment]
This isn't part of the rebalance:
A victim would call either `ArrakisV2Router::swapAndAddLiquidity` or `swapAndAddLiquidityPermit2` for a swap. A malicious actor would see this and front run with another call to the Router, not actually doing a swap, but increasing the allowance for the token the victim wanted to swap. Thus DoS the victims call.

Very similar to the abuse path described in:
https://gist.github.com/kassandraoftroy/6ab217b265b29ce7c33106e5d57bbe4b#1-dos-of-routerswapexecutor-with-non-zero-approvals 

But instead of abusing approval == 0, here the abuse is using a very high approval that would overflow the addition performed in the OZ lib.

**Comment by hrishibhat** [comment]
@0ximmeas 
The lead watsons comment on this issue:
>  I see this a temporary DOS that can be reversed the exact same way it was done. And what would be the point? Deposits aren't time sensitive and the attacker woudln't gain anything by doing this

The comment makes sense, I don't see a valid impact to consider this a medium.

**Comment by hrishibhat** [comment]
Result:
Low
Unique 
The impact of the issue is not a valid medium. Agree with the Lead Watson comment quoted above, considering this a low

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0ximmeas](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/168/#issuecomment-1635961488): rejected
