### ISSUE TITLE
0x52 - ArrakisStorageV2#initialize allows whitelisting token0 and token1 as routers

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#179]
0x52

medium

# ArrakisStorageV2#initialize allows whitelisting token0 and token1 as routers

## Summary

When initializing ArrakisV2Storage the _whitelistRouters subcall takes place before token0 and token1 are set allowing them to be added as routers. This allows honeypotting users since the calls to those contracts can be used to drain both the contents of the contract and anyone to has an allowance to the vault (which is why they are blocked to begin with).

## Vulnerability Detail

[ArrakisV2Storage.sol#L134-L137](https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/abstract/ArrakisV2Storage.sol#L134-L137)

        _whitelistRouters(params_.routers);

        token0 = IERC20(params_.token0);
        token1 = IERC20(params_.token1);

Here we see in the initialize that _whitelistRouters is called before token0 and token1 are set.

[ArrakisV2Storage.sol#L311-L324](https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/abstract/ArrakisV2Storage.sol#L311-L324)

    function _whitelistRouters(address[] calldata routers_) internal {
        for (uint256 i = 0; i < routers_.length; i++) {
            require(
                routers_[i] != address(token0) &&
                    routers_[i] != address(token1),
                "RT"
            );
            require(!_routers.contains(routers_[i]), "CR");
            // explicit.
            _routers.add(routers_[i]);
        }
        emit LogWhitelistRouters(routers_);
    } 

Above we see that token0 and token1 are checked to block whitelisting the tokens are routers (which can receive calls directly). The problem is that since token0 and token1 are not set yet, the token addresses are fully valid. This allows keepers to directly steal funds from anyone that has created an allowance to the vault contract. As stated in the readme, keepers are only semi-trusted and should only be able to grief the vault. This is a clear violation of that. 

## Impact

Keepers can steal funds from any user with an allowance to the vault

## Code Snippet

[ArrakisV2Storage.sol#L118-L149](https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/abstract/ArrakisV2Storage.sol#L118-L149)

## Tool used

Manual Review

## Recommendation

Change the order of the calls:

    -   _whitelistRouters(params_.routers);

        token0 = IERC20(params_.token0);
        token1 = IERC20(params_.token1);

    +   _whitelistRouters(params_.routers);

        _transferOwnership(params_.owner);

**Comment by eliteWalrus4164** [comment]
Escalate

While this is a nice trick, this finding is out of scope since vault owner/creator is fully trusted as per contest rules

**Comment by sherlock-admin** [comment]
> Escalate
> 
> While this is a nice trick, this finding is out of scope since vault owner/creator is fully trusted as per contest rules

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
the duplicate https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/82 summarize a more severe impact (ˇˍˇ)

**Comment by syjcnss** [comment]
#82 is an interesting one.

I think the swap slippage check will block the attacker from stealing funds using the `swap.router.call` that is described in #82.

If it doesn't block, then the `multicall` trick used in [#187 (comment) ](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/187#issuecomment-1636038030) is also possible to launch a similar attack by swapping the token0/token1 out to a `recipient` set by the attacker. It will be a new vulnerability that is not submited in this contest.

Anyway, the attack in #82 originates from a trusted role. If someone can prove that swap slippage check could be bypassed when stealing funds inside `swap.router.call`, then we can have another new vulnerability.

**Comment by eliteWalrus4164** [comment]
While I agree there is a mistake in the initialization flow, the admin is trusted to initialize correctly.
There are all sorts of simple things the initializing admin can do to harm users such as setting a malicious manager or owner

referencing sponsor's post in public discord (step 1.):
![Screen Shot 2023-07-18 at 10 39 58](https://github.com/sherlock-audit/2023-06-arrakis-judging/assets/6078372/a1f6b366-2d34-4144-8a21-404be929005d)

**Comment by 0xpinky** [comment]
Its input validation. This function is called by the trusted party. I think its low.

**Comment by boulderbytes** [comment]
It's obviously clear that there's a mistake in the flow. The issue is the consequence of the unintended code flow and not of the input validation. It just happen to be an admin function, still it doesn't behave as expected nor as intended. If the team would be aware of this flow mistake, it would change the code and not initialize differently. And that's precisely what they already indicated. It's not the same as setting a malicious owner or something else as in that case the code would execute exactly as expected.

**Comment by 0xpinky** [comment]
its something missing of zero address check... setting zero address would lead to unintended error.

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
While there is an incorrect flow here, for there to be a loss of funds, this requires a mistake by the owner to whitelist a token as a router. 
Admin/Owners by default are trusted with the inputs when initializing a contract. So this would be low according to Sherlock rules.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [SergeKireev](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/179/#issuecomment-1637085859): accepted

**Comment by Gevarist** [comment]
We now initialize tokens before whitelisting routers.
PR : https://github.com/ArrakisFinance/v2-core/pull/159
fix : https://github.com/ArrakisFinance/v2-core/blob/840d46ea1765fa737824d47b400c639c6210fbad/contracts/abstract/ArrakisV2Storage.sol#L142

**Comment by IAm0x52** [comment]
Fix looks good. Order has been changed to whitelist routers after setting `token0` and `token1`
