### ISSUE TITLE
0x52 - SimpleManager#rebalance fails to check if burned pools are unbalanced

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#181]
0x52

medium

# SimpleManager#rebalance fails to check if burned pools are unbalanced

## Summary

SimpleManager checks that all pools being minted to are balanced within a certain threshold. This prevents the contract from minting to unbalanced pools to protect it from sandwich attacks. The problem is that it doesn't check for pools that are burned from but not minted too. Burning unbalanced pools are just as damaging as minting to them which can lead to losses due to sandwich attacks. 

## Vulnerability Detail

[SimpleManager.sol#L157-L198](https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-manager-templates/contracts/SimpleManager.sol#L157-L198)

        if (mintsLength > 0) {
            checked = new uint24[](mintsLength);
            oraclePrice = vaultInfo.oracle.getPrice0();
        }

        for (uint256 i; i < mintsLength; ++i) {

            ...

            _checkDeviation(
                poolPrice,
                oraclePrice,
                vaultInfo.maxDeviation,
                token1Decimals
            );

            checked[increment] = rebalanceParams_.mints[i].range.feeTier;
            increment++;
        }

In the code above the pool price of each minting pool is validated against the expected price from the oracle. This disallows minting to unbalanced pool. This check doesn't, however, account for pools that are being burned from. This allows those burns to be sandwich attacked.

## Impact

Pools that are burned from but not minted to can be sandwich attacked

## Code Snippet

[SimpleManager.sol#L128-L214](https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-manager-templates/contracts/SimpleManager.sol#L128-L214)

## Tool used

Manual Review

## Recommendation

SimpleManager#rebalance should check pools burned from as well.

**Comment by eliteWalrus4164** [comment]
Escalate

Severity should be low on this one, since if the pool is deviated from 'real price', removing liquidity is actually at the advantage of the burner

If we consider that Bob is the operator withdrawing liquidity, and Alice the sandwicher,
By first deviating the pool, Alice swaps tokenA at unfavorable prices.

Bob removes liquidity, and takes in what we can call `impermanent wins` essentially emptying ranges of liquidity containing more of tokenA compared to 'real price'

Alice has to swap back by providing tokenBs but since liquidity is now reduced, Alice takes a big loss on the way back

**Comment by sherlock-admin** [comment]
> Escalate
> 
> Severity should be low on this one, since if the pool is deviated from 'real price', removing liquidity is actually at the advantage of the burner
> 
> If we consider that Bob is the operator withdrawing liquidity, and Alice the sandwicher,
> By first deviating the pool, Alice swaps tokenA at unfavorable prices.
> 
> Bob removes liquidity, and takes in what we can call `impermanent wins` essentially emptying ranges of liquidity containing more of tokenA compared to 'real price'
> 
> Alice has to swap back by providing tokenBs but since liquidity is now reduced, Alice takes a big loss on the way back

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by syjcnss** [comment]
Agree with @SergeKireev 

Sandwich attack liqudity buring will not profit the attacker.

And I've also expressed the same idea in real-wagmi

* https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/92#issuecomment-1632438043

**Comment by ctf-sec** [comment]
Agree with the escalation

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with the Escalation. Considering this a low issue

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [SergeKireev](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/181/#issuecomment-1636305780): accepted
