### ISSUE TITLE
BenRai - OOG for unbound loop for `_ranges` leads to stuck funds in vault

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#20]
BenRai

high

# OOG for unbound loop for `_ranges` leads to stuck funds in vault

## Summary
If the length of the array `_ranges` in `ArrakisV2.sol` gets to long the function `burn` will run out of gas and users will not be able to withdraw any funds

## Vulnerability Detail
If a user wants to withdraw his assets from a vault, he calls the function `burn` in `ArrakisV2.sol`. This function iterates over the array of `_ranges` and proportionally burns liquidity in each `range` the vault is invested in. If the number of ranges is to big, the function will run out of gas and the user will not be able to withdraw his assets.  

## Impact
If users can not withdraw their assets at any time, the reputation of Arrakis will be damaged and user will not deposit additional funds into other vaults and will move the funds they have already deposited to other projects.

## Code Snippet
https://github.com/sherlock-audit/2023-06-arrakis/blob/9594cf930307ebbfe5cae4f8ad9e9b40b26c9fec/v2-core/contracts/ArrakisV2.sol#L175-L204

## Tool used

Manual Review

## Recommendation

Limit the number of ranges a vault can enter to prevent this issue

Duplicate of #27

**Comment by BenRai1** [comment]
Escalate

Same as https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/27

See https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/27 for discussion of validity

**Comment by sherlock-admin** [comment]
> Escalate
> 
> Same as https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/27
> 
> See https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/27 for discussion of validity

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Result:
Low
Duplicate of #27

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [BenRai1](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/20/#issuecomment-1637001218): accepted
