### ISSUE TITLE
PRAISE - Hardcoded  GRACE_PERIOD_TIME(12 hours) won't be the same on chains like  optimism

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#24]
PRAISE

medium

# Hardcoded  GRACE_PERIOD_TIME(12 hours) won't be the same on chains like  optimism

## Summary
blockTime can be shorter on some L2's.

## Vulnerability Detail
On Mainnet it takes 12s to mine a single block, and a minute to mine 5 blocks. so hardcoded [GRACE_PERIOD_TIME()](https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-manager-templates/contracts/oracles/ChainLinkOracle.sol#L15) which is 3600 here is 12 hours (_it is gotten like this_: 5x60x12). 

But on optimism it takes 2s to mine a single block, and a minute to mine 30 blocks. Therefore 12 hours will be 21600 (30x60x12)

Hardcoded  GRACE_PERIOD_TIME(3600) will be less than 12 hours on optimism

## Impact
Hardcoded  GRACE_PERIOD_TIME(3600) will be less than 12 hours on optimism

## Code Snippet
https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-manager-templates/contracts/oracles/ChainLinkOracle.sol#L15
## Tool used

Manual Review

## Recommendation
don't hardcode blocktime in a multichain project.

**Comment by Love4codes** [comment]
Escalate for 10 USDC
The hardcoded GRACE_PERIOD_TIME(3600) will be less than 12 hours on optimism.
It will affect ChainLinkOracle._checkSquencer() [see here](https://github.com/sherlock-audit/2023-06-arrakis/blob/9594cf930307ebbfe5cae4f8ad9e9b40b26c9fec/v2-manager-templates/contracts/oracles/ChainLinkOracle.sol#L157-L160)

**Comment by sherlock-admin** [comment]
> Escalate 
> The hardcoded GRACE_PERIOD_TIME(3600) will be less than 12 hours on optimism.
> It will affect ChainLinkOracle._checkSequencer() [see here](https://github.com/sherlock-audit/2023-06-arrakis/blob/9594cf930307ebbfe5cae4f8ad9e9b40b26c9fec/v2-manager-templates/contracts/oracles/ChainLinkOracle.sol#L157-L160)
> 
> According to the comments by the devs, grace period is supposed to have passed after the sequencer is back up and that's the purpose of the check in ChainLinkOracle._checkSequencer().
> 
> The GRACE_PERIOD_TIME(3600) is supposed to be 12 hours but on optimism 12 hours is 21600
> 
> The issue now is that the GRACE_PERIOD_TIME(3600) won't be up to 12 hours on optimism, it will be something extremely smaller

    You've deleted an escalation for this issue.

**Comment by ctf-sec** [comment]
I find it difficult to believe this is a issue, the recommendation from openzeppelin use the same value:

https://docs.chain.link/data-feeds/l2-sequencer-feeds#example-code

> This example code works on the Arbitrum, Optimism, and Metis networks.

**Comment by Love4codes** [comment]
> I find it difficult to believe this is a issue, the recommendation from openzeppelin use the same value:
> 
> https://docs.chain.link/data-feeds/l2-sequencer-feeds#example-code
> 
> > This example code works on the Arbitrum, Optimism, and Metis networks.

Thank you, i've withdrawn my escalation based on the fact that OZ used the same value
