### ISSUE TITLE
cergyk - Withdraw DOS through unbounded _ranges array

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#27]
cergyk

high

# Withdraw DOS through unbounded _ranges array

## Summary
A malicious operator can prevent vault depositors from withdrawing their funds by stuffing the `_ranges` array.

## Vulnerability Detail
A malicious operator can call rebalance to provide dust amounts of liquidity on a very large number of ranges, to stuff the unbounded `_ranges` array in `ArrakisV2`:
https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/ArrakisV2.sol#L395

This will cause a DOS for users trying to withdraw:
https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/ArrakisV2.sol#L175

If the `_ranges` array is very large, they will encounter out of gas error, and be denied the withdrawal of their funds

## Impact
Funds are stuck, vault depositors are unable to withdraw;

## Tool used

Manual Review

## Recommendation
Bound the number of ranges which can be managed on a single vault.

**Comment by eliteWalrus4164** [comment]
Escalate

Not sure why it was excluded, operator is a semi-trusted role, he should not be able to brick user funds indefinitely

**Comment by sherlock-admin** [comment]
> Escalate
> 
> Not sure why it was excluded, operator is a semi-trusted role, he should not be able to brick user funds indefinitely

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by syjcnss** [comment]
This should be of low severity.

I agree that a malicious operator can do this DOS but not indefinitely.

If the owner finds that the operator is doing this, the owner can replace the malicious operator with a good one by calling the `removeOperators` and `addOperators` functions.

The good operator is able to burn the stuffed `_ranges` entries easily by calling `rebalance` function. This operation is not gas costy and requires the same level of gas that the attacker used.

https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/ArrakisV2.sol#L294-L295
```
                if (liquidityToWithdraw == liquidity) {
                    (bool exists, uint256 index) = Position.rangeExists(
                        _ranges,
                        rebalanceParams_.burns[i].range
                    );
                    require(exists, "RRNE");

                    _ranges[index] = _ranges[_ranges.length - 1];
                    _ranges.pop();
                }
```

`rangeExists` will loop the `_ranges` array but it will stop once it finds the target entries. The loop count will be the valid range count which will be a small number.

```
    function rangeExists(Range[] memory currentRanges_, Range memory range_)
        public
        pure
        returns (bool ok, uint256 index)
    {
        for (uint256 i; i < currentRanges_.length; i++) {
            ok =
                range_.lowerTick == currentRanges_[i].lowerTick &&
                range_.upperTick == currentRanges_[i].upperTick &&
                range_.feeTier == currentRanges_[i].feeTier;
            if (ok) {
                index = i;
                break;
            }
        }
    }
```

So the DOS is not permanent and won't cause losses to the protocol.

**Comment by ctf-sec** [comment]
https://docs.sherlock.xyz/audits/judging/judging#some-standards-observed

> Could Denial-of-Service (DOS), griefing, or locking of contracts count as a Medium (or High) issue? It would not count if the DOS, etc. lasts a known, finite amount of time <1 year. If it will result in funds being inaccessible for >=1 year, then it would count as a loss of funds and be eligible for a Medium or High designation. The greater the cost of the attack for an attacker, the less severe the issue becomes.

**Comment by hrishibhat** [comment]
@SergeKireev based on the above comments seems like a temporary DOS which can be rectified. And as mentioned in the readme this is expected and not a high/medium based on sherlock rules. 
Do you have anything else to add?

**Comment by eliteWalrus4164** [comment]
Agreed, ok to keep closed

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a valid low based on the above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [SergeKireev](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/27/#issuecomment-1636470995): rejected
