### ISSUE TITLE
BenRai - When rebalancing the vault is missing out on potential gains by checking the `maxDeviation` in both directions

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#43]
BenRai

medium

# When rebalancing the vault is missing out on potential gains by checking the `maxDeviation` in both directions

## Summary
When rebalancing the vault, the current price of the oracle is compared to the current price of the uniswapV3 pool. The absolute deviation between both prices is checked making the vault miss out on potential gains.

## Vulnerability Detail

The price of an oracle is calculated by aggregating several prices from different trusted sources and calculating the average of those prices. Since the price returned by the oracle is an average this means it is possible that the price in the Uniswap pool is lower or higher than the average, for example if the volume of the Uniswap pool is low. Since Arrakis makes sure that the price from the Oracle is always up to date and the calculations are not working with stale data, rebalancing the vault by checking the price deviation in both direction lets the vault miss out on potential gains if the pool price would be in favour for the vault but outside of the `maxDeviation` threshold.

Example:
`maxDeviation` = 2% 

When rebalancing the vault, the manager wants to swap 1 ETH to USDT. The oracle price for ETH is 1000 USDT, the pool price is 1030 USDT. Since the pool price is outside of the `maxDeviation` of 2% (1020 USDT) the function reverts even though the swap would be beneficial to the vault.

 

## Impact

Vault misses out on additional gains that benefit both users and manager of the vault. Due to compounding interest this can lead to significant lower gains than would have been possible.

## Code Snippet

https://github.com/sherlock-audit/2023-06-arrakis/blob/9594cf930307ebbfe5cae4f8ad9e9b40b26c9fec/v2-manager-templates/contracts/SimpleManager.sol#L366C30-L385

## Tool used

Manual Review

## Recommendation

Since it is made sure that the oracle prices are stale and not up to date it is safe to only check the deviation if the pool price is lower than the oracle price. If it is higher the `maxDeviation` should not be checked since it is in the interest of the vault to receive more from a swap.

**Comment by BenRai1** [comment]
Escalate

As mention in https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/26 this issue is not a dublicat of 26.

I still think it is valid and would be glad to get a feedback on it

**Comment by sherlock-admin** [comment]
> Escalate
> 
> As mention in https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/26 this issue is not a dublicat of 26.
> 
> I still think it is valid and would be glad to get a feedback on it

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
@ctf-sec

**Comment by hrishibhat** [comment]
@ctf-sec

**Comment by ctf-sec** [comment]
Emm not a duplicate of #26 

I think the severity is low

the the price deviation check is to make sure the price is not manipulated

And rebalance is not a trading stragety so having gain is not a priority

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with @ctf-sec the impact is not medium/high.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [BenRai1](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/43/#issuecomment-1636999530): accepted
