### ISSUE TITLE
BugHunter101 - `removeLiquidity` does not check `params_.vault` validity

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#54]
BugHunter101

high

# `removeLiquidity` does not check `params_.vault` validity

## Summary

`removeLiquidity()` does not check `params_.vault` validity, attacker can use a fake `params` and set fake `params_.vault` address, and bypass some check. It will cause attacker steal the fund by calling `removeLiquidity()`

## Vulnerability Detail

As we can see, `removeLiquidity()` does not check `params_.vault` validity, and then will call `_removeLiquidity()`
```solidity
function removeLiquidity(RemoveLiquidityData memory params_)
        external
        whenNotPaused
        nonReentrant
        returns (uint256 amount0, uint256 amount1)
    {
        require(params_.burnAmount > 0, "nothing to burn");
        if (params_.gauge != address(0)) {
            require(
                params_.vault == IGauge(params_.gauge).staking_token(),
                "Incorrect gauge!"
            );
            IGauge(params_.gauge).claim_rewards(msg.sender);
            IERC20(params_.gauge).safeTransferFrom(
                msg.sender,
                address(this),
                params_.burnAmount
            );

            IGauge(params_.gauge).withdraw(params_.burnAmount);
        } else {
            IERC20(params_.vault).safeTransferFrom(
                msg.sender,
                address(this),
                params_.burnAmount
            );
        }

        (amount0, amount1) = _removeLiquidity(params_);//@audit
    }
```
and the `_removeLiquidity()` aslo does not check `params_.vault` validity. ` IArrakisV2(removeData_.vault).burn()` function can be set by attacker to bypass check. Last, attacker set `removeData_.receiveETH = 1`, it will call `_receiveETH` to transfer value .
So that the attacker can steal funds by calling removeLiquidity()
```solidity
function _removeLiquidity(RemoveLiquidityData memory removeData_)
        internal
        returns (uint256 amount0, uint256 amount1)
    {
        if (removeData_.receiveETH) {
            (amount0, amount1) = IArrakisV2(removeData_.vault).burn(
                removeData_.burnAmount,
                address(this)
            );
        } else {
            (amount0, amount1) = IArrakisV2(removeData_.vault).burn(
                removeData_.burnAmount,
                removeData_.receiver
            );
        }

        require(
            amount0 >= removeData_.amount0Min &&
                amount1 >= removeData_.amount1Min,
            "received below minimum"
        );

        if (removeData_.receiveETH) {
            _receiveETH(//@audit
                IArrakisV2(removeData_.vault),
                amount0,
                amount1,
                removeData_.receiver
            );
        }
    }
```

## Impact

It will cause user loss fund.

## Code Snippet

https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-periphery/contracts/ArrakisV2Router.sol#L559

https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-periphery/contracts/ArrakisV2Router.sol#L229

## Tool used

Manual Review

## Recommendation

Check `params_.vault` validity

Duplicate of #194

**Comment by Dlangman** [comment]
Escalate
I think the risk of vulnerability exists

**Comment by sherlock-admin** [comment]
> Escalate
> I think the risk of vulnerability exists
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
> Escalate I think the risk of vulnerability exists

Is there are anything you want to reply after checking the sponsor's response?

https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/194

I mean, is the Router designed to hold funds?

**Comment by hrishibhat** [comment]
Result:
Low
Duplicate of #194  
Considering this a Low-issue based on the comment on #194

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Dlangman](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/54/#issuecomment-1636237278): rejected
