### ISSUE TITLE
BenRai - When owner of a vault changes the manager, the old manager misses out on already accumulated fees that are still in the pool

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#63]
BenRai

high

# When owner of a vault changes the manager, the old manager misses out on already accumulated fees that are still in the pool

## Summary

When an owner changes the manager of a vault the current `managerBalance0` and `managerBalance1` are transferred to the old manager but not his share of the already accumulated fees in the pool that have not been withdrawn yet.

## Vulnerability Detail

To changes the manager of an vault, the owner calls the function `setManager()` from `ArrakisV2Srorage.sol`. This function transfers the accumulated `managerBalance0` and `managerBalance1` to the current manager and changes the `manager` variable to a new address. Thereby the old manager misses out on his share of the already accumulated fees in the pool that have not been withdrawn yet.

## Impact

The old manager misses out on his share of the alreaddy collected fees in the pool that have not been withdrawn yet and the new manager inherits this share without having to work for it

## Code Snippet

https://github.com/sherlock-audit/2023-06-arrakis/blob/9594cf930307ebbfe5cae4f8ad9e9b40b26c9fec/v2-core/contracts/abstract/ArrakisV2Storage.sol#L209C4-L213

https://github.com/sherlock-audit/2023-06-arrakis/blob/9594cf930307ebbfe5cae4f8ad9e9b40b26c9fec/v2-core/contracts/abstract/ArrakisV2Storage.sol#L273-L289

## Tool used

Manual Review

## Recommendation

Before the manager is changed, all ranges of the pool should be called with a burn request of 0. This would update the tokens owed for the position which then can be withdrawn by calling `collect` for the position. Once the fees have been collected the `managerBalances` in the vault can be updated and the old manager gets the fees he is owed

Duplicate of #94

**Comment by BenRai1** [comment]
Escalate 

Same as https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/94

Discussion why it is valid can be seen at https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/94

**Comment by sherlock-admin** [comment]
> Escalate 
> 
> Same as https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/94
> 
> Discussion why it is valid can be seen at https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/94
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JeffCX** [comment]
Yes, can use #94 as major thread of discussion

**Comment by hrishibhat** [comment]
Result:
Low
Duplicate of #94 
Considering this issue a duplicate of #94. the final severity of this issue will be based on resolution of #94

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [BenRai1](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/63/#issuecomment-1636999116): accepted
