### ISSUE TITLE
Auditwolf - Resolver returns incorrect values for function swapandaddliquidity.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#81]
Auditwolf

high

# Resolver returns incorrect values for function swapandaddliquidity.

## Summary

In order for Internal function swapandaddliquidity  to determine amount0, amount1 and shares received it calls function getmintamounts of the resolver with amount 0 use , amount 1 use .  However function getmintamounts uses amount0max , amount1max to determine amount0, amount1 and shares received meaning this return values will be incorrect.

## Vulnerability Detail

First lets see how amount 0 use and amount 1 use is calculated.

        uint256 amount0Use = (params_.swapData.zeroForOne)
            ? params_.addData.amount0Max - amount0Diff
            : params_.addData.amount0Max + amount0Diff;
        uint256 amount1Use = (params_.swapData.zeroForOne)
            ? params_.addData.amount1Max + amount1Diff
            : params_.addData.amount1Max - amount1Diff;

Here we can see that depending on boolean swapdata.zeroforone  , we achieve amount0use by subtracting or adding amount0diff to amount0max . similarly we get amount1use by adding or subtracting amount1diff from amount1max. Note that amount0Diff and amount1Diff represent amounts received after a swap. function swapandaddliquidity goes on to call getmintamounts of the resolver with these amount0use and amount1use so as to calculate mintamounts.
Now lets see how the resolver computes the mintamounts.
            mintAmount = UnderlyingHelper.computeMintAmounts(
                current0,
                current1,
                totalSupply,
                amount0Max_,
                amount1Max_
 As we can see the function getmintamounts of the resolver determines the mintamount by calling underlyinghelper with the values of current0 , current1, totalsupply , amount0max and amount1max.  earlier we saw that amount1use and amount0use are completely different from amount0max and amount1max . therefore , the mintamounts returned by the resolver will be totally incorrect. Now function swapandaddliquidity checks these values using the require statement below.
        require(
            amount0 >= params_.addData.amount0Min &&
                amount1 >= params_.addData.amount1Min &&
                sharesReceived >= params_.addData.amountSharesMin,
            "below min amounts"
        );
Due to the incorrect values of amount0 , amount1 and sharesReceived this check will either always pass or always fails.

## Impact
If this check always pass , internal function addliquidity will execute with incorrect values meaning incorrect amounts will be minted to the receiver.
On the contrary ,if this check always fails , users will not be able to swapandaddliquidity.

## Code Snippet
https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-periphery/contracts/ArrakisV2Router.sol#L451C1-L535C1

https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/ArrakisV2Resolver.sol#L145C2-L185C15

## Tool used

Manual Review

## Recommendation
Add a way to call the getmintamounts function of the resolver with amount0use and amount1use.

**Comment by htstarz** [comment]
Escalate for 10 usdc.
Its true amount0use and amount1use is used when calling getmintamounts function of the resolver. However, this function uses amount0max and amount1max to compute mintamounts. Here is a call to the underlying helper with parameters as amount0max and  amount1max.

https://github.com/sherlock-audit/2023-06-arrakis/blob/9594cf930307ebbfe5cae4f8ad9e9b40b26c9fec/v2-core/contracts/ArrakisV2Resolver.sol#L174C12-L180C15

mint amount is computed here  https://github.com/sherlock-audit/2023-06-arrakis/blob/9594cf930307ebbfe5cae4f8ad9e9b40b26c9fec/v2-core/contracts/libraries/Underlying.sol#L355C1-L377C15
The issue is that the underlying helper will calculate mint amount using amount0max and amount1max instead of amount0use and  amount1use in the process of swapping and adding liquidity. 
I think there was a misunderstanding in the recommendation I  suggested.

**Comment by sherlock-admin** [comment]
> Escalate for 10 usdc.
> Its true amount0use and amount1use is used when calling getmintamounts function of the resolver. However, this function uses amount0max and amount1max to compute mintamounts. Here is a call to the underlying helper with parameters as amount0max and  amount1max.
> 
> https://github.com/sherlock-audit/2023-06-arrakis/blob/9594cf930307ebbfe5cae4f8ad9e9b40b26c9fec/v2-core/contracts/ArrakisV2Resolver.sol#L174C12-L180C15
> 
> mint amount is computed here  https://github.com/sherlock-audit/2023-06-arrakis/blob/9594cf930307ebbfe5cae4f8ad9e9b40b26c9fec/v2-core/contracts/libraries/Underlying.sol#L355C1-L377C15
> The issue is that the underlying helper will calculate mint amount using amount0max and amount1max instead of amount0use and  amount1use in the process of swapping and adding liquidity. 
> I think there was a misunderstanding in the recommendation I  suggested. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
@Gevarist could you have a look at the above escalation comment if the issue is still valid?
cc- @ctf-sec

**Comment by Gevarist** [comment]
@htstarz amount0Max/amount1Max of addData and amount0Max/amount1Max of getMintAmounts are not intended to be the same.

**Comment by htstarz** [comment]
That's true , my point is there is a difference between ( amount0use/ amount1use ) and ( amount0max /amount1max ) which is explained in the submission.  Therefore, amount0use and amount1use should be used when determining mint amounts for function swapandaddliquidity.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
This is a non-issue. 
In the escalation:
>  However, this function uses amount0max and amount1max to compute mintamounts.

these values are just that parameters passed inside `getmintamounts` view function. 
Do not see a valid issue here.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [htstarz](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/81/#issuecomment-1636331082): rejected
