### ISSUE TITLE
rvierdiiev - ArrakisV2 may not take manager fee for tokens with low decimals

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#93]
rvierdiiev

medium

# ArrakisV2 may not take manager fee for tokens with low decimals

## Summary
ArrakisV2 may not take manager fee for tokens with low decimals. Because of that manager will not receive all fees.
## Vulnerability Detail
When `burn` function is called, then it loops through the all ranges, in order to withdraw it from uniswap for user.
Also fees for each range [is collected](https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/ArrakisV2.sol#L433-L439).

For their job, managers can get a fee which is handled [by `_applyFees` function](https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/ArrakisV2.sol#L208).

https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/ArrakisV2.sol#L445-L449
```solidity
    function _applyFees(uint256 fee0_, uint256 fee1_) internal {
        uint16 mManagerFeeBPS = managerFeeBPS;
        managerBalance0 += (fee0_ * mManagerFeeBPS) / hundredPercent;
        managerBalance1 += (fee1_ * mManagerFeeBPS) / hundredPercent;
    }
```
As you can see this function just takes manager's percentage out of max 10_000 bips.

Fees that are collected can be not big at all, because they are collected each burn and rebalance(with burn) call.
Some tokens that have low decimals amount as GUSD(2 decimals) in this case may not work as expected.

For example, manager has fee of 0.5%, which is 50 bips.
And during collect, 1$ were earned in GUSD, which is 100 tokens.
Then fee = 100 * 50 / 10000, which will give 0 amount for the manager. 
But if you compare this with usdc token which uses 6 decimals, then in this case manager will receive fee for same 1$ of collected fees.
## Impact
Manager will not receive fair fees for some tokens.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
Don't know how to handle it. Looks like managers should be announced, that low decimals tokens may have less fees payouts for them.

**Comment by rvierdiyev** [comment]
Escalate.
I think this should be checked as such tokens were in the scope.

**Comment by ctf-sec** [comment]
https://github.com/sherlock-audit/2023-06-arrakis/blob/9594cf930307ebbfe5cae4f8ad9e9b40b26c9fec/v2-core/contracts/abstract/ArrakisV2Storage.sol#L218

Please check 

```solidity
    /// @notice set manager fee bps
    /// @param managerFeeBPS_ manager fee in basis points.
    /// @dev only callable by manager.
    function setManagerFeeBPS(uint16 managerFeeBPS_) external onlyManager {
        require(managerFeeBPS_ <= 10000, "MFO");
        managerFeeBPS = managerFeeBPS_;
        emit LogSetManagerFeeBPS(managerFeeBPS_);
    }
```

the hundredPercent is hardcoded to 10_000, but manager can adjust the managerFeeBPS, don't think this is a issue

**Comment by rvierdiiev** [comment]
> the hundredPercent is hardcoded to 10_000, but manager can adjust the managerFeeBPS, don't think this is a issue

this is true, and in the issue i have described when this will not work for some tokens

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering the issue low as it impacts only extremely low decimal tokens.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [rvierdiyev](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/93/#issuecomment-1635951110): rejected

**Comment by rvierdiiev** [comment]
@hrishibhat 
described token is in the scope
i don't see the reason, why this should be low.
