### ISSUE TITLE
rvierdiiev - ArrakisV2Storage.setManager doesn't collect all manager's fees

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#94]
rvierdiiev

medium

# ArrakisV2Storage.setManager doesn't collect all manager's fees

## Summary
ArrakisV2Storage.setManager doesn't collect all manager's fees
## Vulnerability Detail
Manager earns fees, that are accumulated into `managerBalance0` and `managerBalance1` variables. These fees are collected, only when [withdraw is done](https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/ArrakisV2.sol#L433-L439) from uniswap, because withdraw calls `collect`.

Manager of vault [can be changed](https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/abstract/ArrakisV2Storage.sol#L209-L213). This will [send all accumulated fees to the current manager](https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/abstract/ArrakisV2Storage.sol#L273-L289).

The problem is that not all fees are collected for the manager and as result he losses some of them. In order to pay all his fees, then `burn` with 0 liquidity should be done for all ranges and then `collect` should be called and fees should be accrued.
## Impact
Previous manager doesn't receive all earned fees.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
Collect fees for all existing ranges and accrued them to current manager, before the change.

**Comment by rvierdiyev** [comment]
Escalate.
The fact that before new manager is added then all fees are withdrawn to previous manager, means that contract is going to be fair with previous manager and pay all his earned fees.
In order to do that correctly, fees should be collected before changing manager.

**Comment by ctf-sec** [comment]
Seems like a design choice and it is admin's choice not to collect fee before changing manager.

**Comment by rvierdiiev** [comment]
As these fees don't belong to the owner and he has no ability to get them, they are supposed to belong to manager.
In case if manager has changed, those fees should be correctly paid out to him. For example, each simple manager [has owner](https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-manager-templates/contracts/SimpleManager.sol#L33C27-L33C45) and this owner should receive fees. Note, that `manager.owner != vault.owner`, which means that vault owner should pay correctly to the manager's owner, once he decided to change him.

**Comment by BenRai1** [comment]
Also if the manager is changed the fees the old manager is not getting will be payed out to the new manager ever though he did not do any “managing” so far. I have the same issue, should I also escalate it or is it enough to mention it here?

**Comment by ctf-sec** [comment]
You are welcome to escalate but very unlike it is will be a medium in sherlock standard : at most low

**Comment by rvierdiiev** [comment]
Do not agree, as it's loss of fees.

**Comment by BenRai1** [comment]
Just for my understanding: why is it supposed to be low? Like stated by rvierdiyev above the protocol is set up to be fair towards the old manager since it send the accumulated fees to him. Since the fees accumulated in the pools belong to the manager they should also be send to the old manager. Depending on the time the fees were updated last, the amound the manager is missing out can be significant. So why low? Just want to learn so I can reduce my invalid submissions in the future :)

**Comment by JeffCX** [comment]
https://docs.sherlock.xyz/audits/judging/judging

> Admin could have an incorrect call order. Example: If an Admin forgets to setWithdrawAddress() before calling withdrawAll() This is not a valid issue

**Comment by Jeiwan** [comment]
Escalate

This is a valid issue. And I believe it's high severity because managers lose a portion of their rewards due to the bug. Managers do the hard work of balancing vaults to increase the profitability of depositors. However, due to the bug, a portion of rewards will be lost when a manager is changed. This is a clear loss of funds for managers.

See #242 for some more details.

**Comment by sherlock-admin** [comment]
> Escalate
> 
> This is a valid issue. And I believe it's high severity because managers lose a portion of their rewards due to the bug. Managers do the hard work of balancing vaults to increase the profitability of depositors. However, due to the bug, a portion of rewards will be lost when a manager is changed. This is a clear loss of funds for managers.
> 
> See #242 for some more details.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Just want to sync the comments from Jeiwan made in 242, can use this thread for major discussion

This is clearly NOT a manager's mistake. A manager cannot collect those fees unless they add or remove liquidity. The contract is clearly designed to collect the fees that the old manager has earned:
https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/abstract/ArrakisV2Storage.sol#L210
But the function collects only accumulated fees, not the pending ones.

@hrishibhat Could I please ask you to resolve the escalations of the contest? I'm seriously worried that the assigned judge is not capable of handling them properly.

**Comment by ctf-sec** [comment]
Let me help you phrase the issue and it will decide if the report is valid for a medium or low

If all duplicates, the report highlights: when changing manager, the fee is lost

But the report #242 highlight a issue in the _withdrawManagerBalance itself because the function does not [collect](https://github.com/Uniswap/v3-core/blob/main/contracts/UniswapV3Pool.sol#L503-L510)

In the current codebase, when user mint or burn the function collect is called

there is also a function that can be used to collect fee permissionless

[here](https://github.com/sherlock-audit/2023-06-arrakis/blob/9594cf930307ebbfe5cae4f8ad9e9b40b26c9fec/v2-core/contracts/ArrakisV2.sol#L417)

```solidity
    function withdrawManagerBalance() external nonReentrant {
        _withdrawManagerBalance();
    }
```

so if there are prove that prove _withdrawManagerBalance's logic is flawed and result in loss of fee, it maybe a valid medium

if not, withdrawManagerBalance can call permissionless to collect fees.

no need to be mad 👍 that does not help resolve the escalation :)

**Comment by syjcnss** [comment]
I think this is just a design choice.

There are also situations in which the admin doesn't want the old manager to collect fees. For example, this can occur when the manager becomes malicious or when the manager loses their private key.

Without withdrawing the fees, it provides more flexibility for the admin. The admin can set themselves as the manager and collect fees to compensate the previous manager if they believe the manager deserves the fee.

**Comment by Jeiwan** [comment]
> I think this is just a design choice.
> 
> There are also situations in which the admin doesn't want the old manager to collect fees. For example, this can occur when the manager becomes malicious or when the manager loses their private key.
> 
> Without withdrawing the fees, it provides more flexibility for the admin. The admin can set themselves as the manager and collect fees to compensate the previous manager if they believe the manager deserves the fee.

The escalation period is over for this contest. Also, I'd like to remind that the escalation period is for factual commenting, not for expressing of personal opinions.

**Comment by syjcnss** [comment]
@Jeiwan Sorry. Got it, thanks.

**Comment by eliteWalrus4164** [comment]
Some additional elements to help with the judging of this issue:

The sponsor stated that during a standard deployment, the vault creator would renounce ownership over the vault to specifically be unable to change the manager (step 7.)

![Screen Shot 2023-07-18 at 10 39 58](https://github.com/sherlock-audit/2023-06-arrakis-judging/assets/6078372/45d45fc9-8965-4c5c-b0bb-0e78745e01c8)

**Comment by hrishibhat** [comment]
This seems to be the design choice:
https://docs.arrakis.fi/arrakis-v2-core/arrakisv2#withdrawmanagerbalanace

**Comment by rvierdiiev** [comment]
In case if there is documented way to steal someone's funds, that's not design choice, imo.

So what i will do in case of slashed manager, i will frontrun tx to burn with 0 liquidity and withdraw my fees.
So in this case we have another problem, manager still can receive all fees if owner decided to slash him.

**Comment by kassandraoftroy** [comment]
Given that in the "concrete setting" of this audit involves burning the owner and thus having an immutable manager address as pointed out by @SergeKireev, I don't see this issue as valid.

**Comment by hrishibhat** [comment]
> In case if there is documented way to steal someone's funds, that's not design choice, IMO.

I don't think protocol slashing a manager if required can be considered stealing funds. 
And from the context of this scope these managers are trusted.

> So in this case we have another problem, manager still can receive all fees if owner decided to slash him.

so in addition to this and the sponsor  comment above don't see there is a valid medium here.

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
Based on the above comments, considering this a low

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [rvierdiyev](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/94/#issuecomment-1635943562): rejected
- [Jeiwan](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/94/#issuecomment-1637071179): rejected
